[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
package = "netlify-deployment-hours-plugin"

  [plugins.inputs]
  # A cron-like expression that expresses when a deployment can occur
  expression = "* 17-19 * * *"
  # tz database value that expresses the timezone of the expression
  timezone = "Asia/Kolkata"


